### ISSUE TITLE
Face detection in a image using opencv

### ISSUE THREAD

**Issue by sujal-garg** [Developer-Student-Clubs-MMDU/Data-Science#4]

**Comment by ren276** [comment]
can you put a hactoberfest tag on this issues ! Then I can start the solving

**Comment by ren276** [comment]
In addition to it , Can you assign it to me as I have already done it using HarrCascade !

**Comment by ren276** [comment]
thanks for adding the labels ! Now can you assign to me as i can solve it !

**Comment by 7sakshi7** [comment]
ok
